services:
  app:
    build:
      target: "prod"
    volumes:
    networks:
      - https_network
      - digicore
    restart: always

  prisma_studio:
    build:
      target: "prod-prisma"
    ports:
      - "${PRISMA_PORT}:5555"
    networks:
      - https_network
      - digicore
    restart: always

  db:
    image: "mysql:8.1.0@sha256:eb00f19a38312b85bfb7195eead2d07d35279f2a6a61b3dc994094dcefa57986"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - https_network
      - digicore
    restart: always

volumes:
  db_data:
  app_node_modules:

networks:
  https_network:
    external: true
  digicore:
    external: true
