services:
  app:
    build:
      target: "dev"
    volumes:
      - "./:/app"
      - "app_node_modules:/app/node_modules"
    ports:
      - "${APP_PORT}:3000"

  prisma_studio:
    build:
      target: "dev_prisma_studio"
    volumes:
      - "./:/app"
      - "prisma_studio_node_modules:/app/node_modules"
    ports:
      - "${PRISMA_PORT}:5555"

  db:
    image: "mysql:8.1.0@sha256:eb00f19a38312b85bfb7195eead2d07d35279f2a6a61b3dc994094dcefa57986"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  db_data:
  app_node_modules:
  prisma_studio_node_modules:
